blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using vulnx
    url: https://github.com/projectdiscovery/vulnx/discussions/categories/q-a
    about: Ask a question or request support for using vulnx

  - name: Share idea / feature to discuss for vulnx
    url: https://github.com/projectdiscovery/vulnx/discussions/categories/ideas
    about: Share idea / feature to discuss for vulnx

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication
